/***************************************************************************
 * This program is Copyright (C) 1986, 1987, 1988 by Jonathan Payne.  JOVE *
 * is provided to you without charge, and with no warranty.  You may give  *
 * away copies of JOVE, including sources, provided that this notice is    *
 * included in all the files.                                              *
 ***************************************************************************/

/* Warning:  You probably shouldn't put ifdefs anywhere *inside* the keymaps
   definitions.	 It'll screw up the stuff in comments (at least), and maybe
   a few other things.	Yes, it *WILL* screw up the comments ... but it's
   not clear that you care ... */

#include "jove.h"

data_obj *MainKeys[NCHARS] = {
	(data_obj *) &commands[182],	/* C-@ */
	(data_obj *) &commands[16],	/* C-A */
	(data_obj *) &commands[7],	/* C-B */
	(data_obj *) 0,                 /* C-C */
	(data_obj *) &commands[44],	/* C-D */
	(data_obj *) &commands[69],	/* C-E */
	(data_obj *) &commands[85],	/* C-F */
	(data_obj *) 0,                 /* C-G */
	(data_obj *) &commands[46],	/* C-H */
	(data_obj *) &commands[97],	/* C-I */
	(data_obj *) &commands[122],	/* C-J */
	(data_obj *) &commands[110],	/* C-K */
	(data_obj *) &commands[152],	/* C-L */
	(data_obj *) &commands[120],	/* C-M */
	(data_obj *) &commands[124],	/* C-N */
	(data_obj *) &commands[121],	/* C-O */
	(data_obj *) &commands[136],	/* C-P */
	(data_obj *) &commands[149],	/* C-Q */
	(data_obj *) &commands[167],	/* C-R */
	(data_obj *) &commands[165],	/* C-S */
	(data_obj *) &commands[198],	/* C-T */
	(data_obj *) &commands[92],	/* C-U */
	(data_obj *) &commands[125],	/* C-V */
	(data_obj *) &commands[106],	/* C-W */
	(data_obj *) 0,                 /* C-X */
	(data_obj *) &commands[211],	/* C-Y */
	(data_obj *) &commands[164],	/* C-Z */
	(data_obj *) 0,                 /* ESC */
	(data_obj *) &commands[165],	/* C-\ */
#ifndef MSDOS
	(data_obj *) 0,                 /* C-] */
#else /* MSDOS */
	(data_obj *) &commands[83],	/* C-] */
#endif /* MSDOS */
	(data_obj *) &commands[149],	/* C-^ */
	(data_obj *) 0,                 /* C-_ */
	(data_obj *) &commands[180],	/*   */
	(data_obj *) &commands[180],	/* ! */
	(data_obj *) &commands[180],	/* " */
	(data_obj *) &commands[180],	/* # */
	(data_obj *) &commands[180],	/* $ */
	(data_obj *) &commands[180],	/* % */
	(data_obj *) &commands[180],	/* & */
	(data_obj *) &commands[180],	/* ' */
	(data_obj *) &commands[180],	/* ( */
	(data_obj *) &commands[130],	/* ) */
	(data_obj *) &commands[180],	/* * */
	(data_obj *) &commands[180],	/* + */
	(data_obj *) &commands[180],	/* , */
	(data_obj *) &commands[180],	/* - */
	(data_obj *) &commands[180],	/* . */
	(data_obj *) &commands[180],	/* / */
	(data_obj *) &commands[180],	/* 0 */
	(data_obj *) &commands[180],	/* 1 */
	(data_obj *) &commands[180],	/* 2 */
	(data_obj *) &commands[180],	/* 3 */
	(data_obj *) &commands[180],	/* 4 */
	(data_obj *) &commands[180],	/* 5 */
	(data_obj *) &commands[180],	/* 6 */
	(data_obj *) &commands[180],	/* 7 */
	(data_obj *) &commands[180],	/* 8 */
	(data_obj *) &commands[180],	/* 9 */
	(data_obj *) &commands[180],	/* : */
	(data_obj *) &commands[180],	/* ; */
	(data_obj *) &commands[180],	/* < */
	(data_obj *) &commands[180],	/* = */
	(data_obj *) &commands[180],	/* > */
	(data_obj *) &commands[180],	/* ? */
	(data_obj *) &commands[180],	/* @ */
	(data_obj *) &commands[180],	/* A */
	(data_obj *) &commands[180],	/* B */
	(data_obj *) &commands[180],	/* C */
	(data_obj *) &commands[180],	/* D */
	(data_obj *) &commands[180],	/* E */
	(data_obj *) &commands[180],	/* F */
	(data_obj *) &commands[180],	/* G */
	(data_obj *) &commands[180],	/* H */
	(data_obj *) &commands[180],	/* I */
	(data_obj *) &commands[180],	/* J */
	(data_obj *) &commands[180],	/* K */
	(data_obj *) &commands[180],	/* L */
	(data_obj *) &commands[180],	/* M */
	(data_obj *) &commands[180],	/* N */
	(data_obj *) &commands[180],	/* O */
	(data_obj *) &commands[180],	/* P */
	(data_obj *) &commands[180],	/* Q */
	(data_obj *) &commands[180],	/* R */
	(data_obj *) &commands[180],	/* S */
	(data_obj *) &commands[180],	/* T */
	(data_obj *) &commands[180],	/* U */
	(data_obj *) &commands[180],	/* V */
	(data_obj *) &commands[180],	/* W */
	(data_obj *) &commands[180],	/* X */
	(data_obj *) &commands[180],	/* Y */
	(data_obj *) &commands[180],	/* Z */
	(data_obj *) &commands[180],	/* [ */
	(data_obj *) &commands[180],	/* \ */
	(data_obj *) &commands[130],	/* ] */
	(data_obj *) &commands[180],	/* ^ */
	(data_obj *) &commands[180],	/* _ */
	(data_obj *) &commands[180],	/* ` */
	(data_obj *) &commands[180],	/* a */
	(data_obj *) &commands[180],	/* b */
	(data_obj *) &commands[180],	/* c */
	(data_obj *) &commands[180],	/* d */
	(data_obj *) &commands[180],	/* e */
	(data_obj *) &commands[180],	/* f */
	(data_obj *) &commands[180],	/* g */
	(data_obj *) &commands[180],	/* h */
	(data_obj *) &commands[180],	/* i */
	(data_obj *) &commands[180],	/* j */
	(data_obj *) &commands[180],	/* k */
	(data_obj *) &commands[180],	/* l */
	(data_obj *) &commands[180],	/* m */
	(data_obj *) &commands[180],	/* n */
	(data_obj *) &commands[180],	/* o */
	(data_obj *) &commands[180],	/* p */
	(data_obj *) &commands[180],	/* q */
	(data_obj *) &commands[180],	/* r */
	(data_obj *) &commands[180],	/* s */
	(data_obj *) &commands[180],	/* t */
	(data_obj *) &commands[180],	/* u */
	(data_obj *) &commands[180],	/* v */
	(data_obj *) &commands[180],	/* w */
	(data_obj *) &commands[180],	/* x */
	(data_obj *) &commands[180],	/* y */
	(data_obj *) &commands[180],	/* z */
	(data_obj *) &commands[180],	/* { */
	(data_obj *) &commands[180],	/* | */
	(data_obj *) &commands[130],	/* } */
	(data_obj *) &commands[180],	/* ~ */
#ifdef ASCII
	(data_obj *) &commands[46],	/* ^? */
#else
	(data_obj *) &commands[46],	/* ^? */
	(data_obj *) &commands[180],	/* M-C-@ */
	(data_obj *) &commands[180],	/* M-C-A */
	(data_obj *) &commands[180],	/* M-C-B */
	(data_obj *) &commands[180],	/* M-C-C */
	(data_obj *) &commands[180],	/* M-C-D */
	(data_obj *) &commands[180],	/* M-C-E */
	(data_obj *) &commands[180],	/* M-C-F */
	(data_obj *) &commands[180],	/* M-C-G */
	(data_obj *) &commands[180],	/* M-C-H */
	(data_obj *) &commands[180],	/* M-C-I */
	(data_obj *) &commands[180],	/* M-C-J */
	(data_obj *) &commands[180],	/* M-C-K */
	(data_obj *) &commands[180],	/* M-C-L */
	(data_obj *) &commands[180],	/* M-C-M */
	(data_obj *) &commands[180],	/* M-C-N */
	(data_obj *) &commands[180],	/* M-C-O */
	(data_obj *) &commands[180],	/* M-C-P */
	(data_obj *) &commands[180],	/* M-C-Q */
	(data_obj *) &commands[180],	/* M-C-R */
	(data_obj *) &commands[180],	/* M-C-S */
	(data_obj *) &commands[180],	/* M-C-T */
	(data_obj *) &commands[180],	/* M-C-U */
	(data_obj *) &commands[180],	/* M-C-V */
	(data_obj *) &commands[180],	/* M-C-W */
	(data_obj *) &commands[180],	/* M-C-X */
	(data_obj *) &commands[180],	/* M-C-Y */
	(data_obj *) &commands[180],	/* M-C-Z */
	(data_obj *) &commands[180],	/* M-ESC */
	(data_obj *) &commands[180],	/* M-C-\ */
	(data_obj *) &commands[180],	/* M-C-] */
	(data_obj *) &commands[180],	/* M-C-^ */
	(data_obj *) &commands[180],	/* M-C-_ */
	(data_obj *) &commands[180],	/* M-  */
	(data_obj *) &commands[180],	/* M-! */
	(data_obj *) &commands[180],	/* M-" */
	(data_obj *) &commands[180],	/* M-# */
	(data_obj *) &commands[180],	/* M-$ */
	(data_obj *) &commands[180],	/* M-% */
	(data_obj *) &commands[180],	/* M-& */
	(data_obj *) &commands[180],	/* M-' */
	(data_obj *) &commands[180],	/* M-( */
	(data_obj *) &commands[180],	/* M-) */
	(data_obj *) &commands[180],	/* M-* */
	(data_obj *) &commands[180],	/* M-+ */
	(data_obj *) &commands[180],	/* M-, */
	(data_obj *) &commands[180],	/* M-- */
	(data_obj *) &commands[180],	/* M-. */
	(data_obj *) &commands[180],	/* M-/ */
	(data_obj *) &commands[180],	/* M-0 */
	(data_obj *) &commands[180],	/* M-1 */
	(data_obj *) &commands[180],	/* M-2 */
	(data_obj *) &commands[180],	/* M-3 */
	(data_obj *) &commands[180],	/* M-4 */
	(data_obj *) &commands[180],	/* M-5 */
	(data_obj *) &commands[180],	/* M-6 */
	(data_obj *) &commands[180],	/* M-7 */
	(data_obj *) &commands[180],	/* M-8 */
	(data_obj *) &commands[180],	/* M-9 */
	(data_obj *) &commands[180],	/* M-: */
	(data_obj *) &commands[180],	/* M-; */
	(data_obj *) &commands[180],	/* M-< */
	(data_obj *) &commands[180],	/* M-= */
	(data_obj *) &commands[180],	/* M-> */
	(data_obj *) &commands[180],	/* M-? */
	(data_obj *) &commands[180],	/* M-@ */
	(data_obj *) &commands[180],	/* M-A */
	(data_obj *) &commands[180],	/* M-B */
	(data_obj *) &commands[180],	/* M-C */
	(data_obj *) &commands[180],	/* M-D */
	(data_obj *) &commands[180],	/* M-E */
	(data_obj *) &commands[180],	/* M-F */
	(data_obj *) &commands[180],	/* M-G */
	(data_obj *) &commands[180],	/* M-H */
	(data_obj *) &commands[180],	/* M-I */
	(data_obj *) &commands[180],	/* M-J */
	(data_obj *) &commands[180],	/* M-K */
	(data_obj *) &commands[180],	/* M-L */
	(data_obj *) &commands[180],	/* M-M */
	(data_obj *) &commands[180],	/* M-N */
	(data_obj *) &commands[180],	/* M-O */
	(data_obj *) &commands[180],	/* M-P */
	(data_obj *) &commands[180],	/* M-Q */
	(data_obj *) &commands[180],	/* M-R */
	(data_obj *) &commands[180],	/* M-S */
	(data_obj *) &commands[180],	/* M-T */
	(data_obj *) &commands[180],	/* M-U */
	(data_obj *) &commands[180],	/* M-V */
	(data_obj *) &commands[180],	/* M-W */
	(data_obj *) &commands[180],	/* M-X */
	(data_obj *) &commands[180],	/* M-Y */
	(data_obj *) &commands[180],	/* M-Z */
	(data_obj *) &commands[180],	/* M-[ */
	(data_obj *) &commands[180],	/* M-\ */
	(data_obj *) &commands[180],	/* M-] */
	(data_obj *) &commands[180],	/* M-^ */
	(data_obj *) &commands[180],	/* M-_ */
	(data_obj *) &commands[180],	/* M-` */
	(data_obj *) &commands[180],	/* M-a */
	(data_obj *) &commands[180],	/* M-b */
	(data_obj *) &commands[180],	/* M-c */
	(data_obj *) &commands[180],	/* M-d */
	(data_obj *) &commands[180],	/* M-e */
	(data_obj *) &commands[180],	/* M-f */
	(data_obj *) &commands[180],	/* M-g */
	(data_obj *) &commands[180],	/* M-h */
	(data_obj *) &commands[180],	/* M-i */
	(data_obj *) &commands[180],	/* M-j */
	(data_obj *) &commands[180],	/* M-k */
	(data_obj *) &commands[180],	/* M-l */
	(data_obj *) &commands[180],	/* M-m */
	(data_obj *) &commands[180],	/* M-n */
	(data_obj *) &commands[180],	/* M-o */
	(data_obj *) &commands[180],	/* M-p */
	(data_obj *) &commands[180],	/* M-q */
	(data_obj *) &commands[180],	/* M-r */
	(data_obj *) &commands[180],	/* M-s */
	(data_obj *) &commands[180],	/* M-t */
	(data_obj *) &commands[180],	/* M-u */
	(data_obj *) &commands[180],	/* M-v */
	(data_obj *) &commands[180],	/* M-w */
	(data_obj *) &commands[180],	/* M-x */
	(data_obj *) &commands[180],	/* M-y */
	(data_obj *) &commands[180],	/* M-z */
	(data_obj *) &commands[180],	/* M-{ */
	(data_obj *) &commands[180],	/* M-| */
	(data_obj *) &commands[180],	/* M-} */
	(data_obj *) &commands[180],	/* M-~ */
#ifdef IBMPC
	(data_obj *) 0,                 /* M-^? */
#else
	(data_obj *) &commands[180],	/* M-^? */
#endif	/* IBMPC */
#endif /* ASCII */
};

data_obj *EscKeys[NCHARS] = {
	(data_obj *) &commands[182],	/* C-@ */
	(data_obj *) 0,                 /* C-A */
	(data_obj *) &commands[10],	/* C-B */
	(data_obj *) 0,                 /* C-C */
	(data_obj *) &commands[65],	/* C-D */
	(data_obj *) 0,                 /* C-E */
	(data_obj *) &commands[88],	/* C-F */
	(data_obj *) 0,                 /* C-G */
	(data_obj *) &commands[104],	/* C-H */
	(data_obj *) 0,                 /* C-I */
	(data_obj *) 0,                 /* C-J */
	(data_obj *) &commands[107],	/* C-K */
	(data_obj *) &commands[32],	/* C-L */
	(data_obj *) 0,                 /* C-M */
	(data_obj *) &commands[86],	/* C-N */
	(data_obj *) 0,                 /* C-O */
	(data_obj *) &commands[8],	/* C-P */
	(data_obj *) 0,                 /* C-Q */
	(data_obj *) 0,                 /* C-R */
	(data_obj *) 0,                 /* C-S */
	(data_obj *) 0,                 /* C-T */
	(data_obj *) &commands[12],	/* C-U */
	(data_obj *) &commands[129],	/* C-V */
	(data_obj *) 0,                 /* C-W */
	(data_obj *) 0,                 /* C-X */
	(data_obj *) 0,                 /* C-Y */
	(data_obj *) 0,                 /* C-Z */
	(data_obj *) 0,                 /* ESC */
	(data_obj *) 0,                 /* C-\ */
	(data_obj *) 0,                 /* C-] */
	(data_obj *) 0,                 /* C-^ */
	(data_obj *) 0,                 /* C-_ */
	(data_obj *) &commands[182],	/*   */
	(data_obj *) 0,                 /* ! */
	(data_obj *) 0,                 /* " */
	(data_obj *) 0,                 /* # */
	(data_obj *) 0,                 /* $ */
	(data_obj *) 0,                 /* % */
	(data_obj *) 0,                 /* & */
	(data_obj *) &commands[149],	/* ' */
	(data_obj *) 0,                 /* ( */
	(data_obj *) 0,                 /* ) */
	(data_obj *) 0,                 /* * */
	(data_obj *) 0,                 /* + */
	(data_obj *) &commands[17],	/* , */
	(data_obj *) &commands[53],	/* - */
	(data_obj *) &commands[70],	/* . */
	(data_obj *) 0,                 /* / */
	(data_obj *) &commands[53],	/* 0 */
	(data_obj *) &commands[53],	/* 1 */
	(data_obj *) &commands[53],	/* 2 */
	(data_obj *) &commands[53],	/* 3 */
	(data_obj *) &commands[53],	/* 4 */
	(data_obj *) &commands[53],	/* 5 */
	(data_obj *) &commands[53],	/* 6 */
	(data_obj *) &commands[53],	/* 7 */
	(data_obj *) &commands[53],	/* 8 */
	(data_obj *) &commands[53],	/* 9 */
	(data_obj *) 0,                 /* : */
	(data_obj *) 0,                 /* ; */
	(data_obj *) &commands[15],	/* < */
	(data_obj *) 0,                 /* = */
	(data_obj *) &commands[68],	/* > */
	(data_obj *) &commands[50],	/* ? */
	(data_obj *) 0,                 /* @ */
	(data_obj *) &commands[11],	/* A */
	(data_obj *) &commands[13],	/* B */
	(data_obj *) &commands[27],	/* C */
	(data_obj *) &commands[103],	/* D */
	(data_obj *) &commands[89],	/* E */
	(data_obj *) &commands[90],	/* F */
	(data_obj *) &commands[94],	/* G */
	(data_obj *) 0,                 /* H */
	(data_obj *) &commands[118],	/* I */
	(data_obj *) &commands[78],	/* J */
	(data_obj *) &commands[111],	/* K */
	(data_obj *) &commands[28],	/* L */
	(data_obj *) &commands[84],	/* M */
	(data_obj *) 0,                 /* N */
	(data_obj *) 0,                 /* O */
	(data_obj *) 0,                 /* P */
	(data_obj *) &commands[147],	/* Q */
	(data_obj *) &commands[156],	/* R */
	(data_obj *) 0,                 /* S */
	(data_obj *) 0,                 /* T */
	(data_obj *) &commands[29],	/* U */
	(data_obj *) &commands[137],	/* V */
	(data_obj *) &commands[34],	/* W */
	(data_obj *) &commands[73],	/* X */
	(data_obj *) &commands[212],	/* Y */
	(data_obj *) &commands[159],	/* Z */
	(data_obj *) &commands[9],	/* [ */
	(data_obj *) &commands[47],	/* \ */
	(data_obj *) &commands[87],	/* ] */
	(data_obj *) 0,                 /* ^ */
	(data_obj *) 0,                 /* _ */
	(data_obj *) 0,                 /* ` */
	(data_obj *) &commands[11],	/* a */
	(data_obj *) &commands[13],	/* b */
	(data_obj *) &commands[27],	/* c */
	(data_obj *) &commands[103],	/* d */
	(data_obj *) &commands[89],	/* e */
	(data_obj *) &commands[90],	/* f */
	(data_obj *) &commands[94],	/* g */
	(data_obj *) 0,                 /* h */
	(data_obj *) &commands[118],	/* i */
	(data_obj *) &commands[78],	/* j */
	(data_obj *) &commands[111],	/* k */
	(data_obj *) &commands[28],	/* l */
	(data_obj *) &commands[84],	/* m */
	(data_obj *) 0,                 /* n */
	(data_obj *) 0,                 /* o */
	(data_obj *) 0,                 /* p */
	(data_obj *) &commands[147],	/* q */
	(data_obj *) &commands[156],	/* r */
	(data_obj *) 0,                 /* s */
	(data_obj *) 0,                 /* t */
	(data_obj *) &commands[29],	/* u */
	(data_obj *) &commands[137],	/* v */
	(data_obj *) &commands[34],	/* w */
	(data_obj *) &commands[73],	/* x */
	(data_obj *) &commands[212],	/* y */
	(data_obj *) &commands[159],	/* z */
	(data_obj *) 0,                 /* { */
	(data_obj *) 0,                 /* | */
	(data_obj *) 0,                 /* } */
	(data_obj *) &commands[116],	/* ~ */
#ifdef ASCII
	(data_obj *) &commands[104],	/* ^? */
#else /* IBMPC or MAC */
	(data_obj *) &commands[104],	/* ^? */
	(data_obj *) 0,                 /* M-C-@ */
	(data_obj *) 0,                 /* M-C-A */
	(data_obj *) 0,                 /* M-C-B */
	(data_obj *) 0,                 /* M-C-C */
	(data_obj *) 0,                 /* M-C-D */
	(data_obj *) 0,                 /* M-C-E */
	(data_obj *) 0,                 /* M-C-F */
	(data_obj *) 0,                 /* M-C-G */
	(data_obj *) 0,                 /* M-C-H */
	(data_obj *) 0,                 /* M-C-I */
	(data_obj *) 0,                 /* M-C-J */
	(data_obj *) 0,                 /* M-C-K */
	(data_obj *) 0,                 /* M-C-L */
	(data_obj *) 0,                 /* M-C-M */
	(data_obj *) 0,                 /* M-C-N */
	(data_obj *) 0,                 /* M-C-O */
	(data_obj *) 0,                 /* M-C-P */
	(data_obj *) 0,                 /* M-C-Q */
	(data_obj *) 0,                 /* M-C-R */
	(data_obj *) 0,                 /* M-C-S */
	(data_obj *) 0,                 /* M-C-T */
	(data_obj *) 0,                 /* M-C-U */
	(data_obj *) 0,                 /* M-C-V */
	(data_obj *) 0,                 /* M-C-W */
	(data_obj *) 0,                 /* M-C-X */
	(data_obj *) 0,                 /* M-C-Y */
	(data_obj *) 0,                 /* M-C-Z */
	(data_obj *) 0,                 /* M-ESC */
	(data_obj *) 0,                 /* M-C-\ */
	(data_obj *) 0,                 /* M-C-] */
	(data_obj *) 0,                 /* M-C-^ */
	(data_obj *) 0,                 /* M-C-_ */
	(data_obj *) 0,                 /* M-  */
	(data_obj *) 0,                 /* M-! */
	(data_obj *) 0,                 /* M-" */
	(data_obj *) 0,                 /* M-# */
	(data_obj *) 0,                 /* M-$ */
	(data_obj *) 0,                 /* M-% */
	(data_obj *) 0,                 /* M-& */
	(data_obj *) 0,                 /* M-' */
	(data_obj *) 0,                 /* M-( */
	(data_obj *) 0,                 /* M-) */
	(data_obj *) 0,                 /* M-* */
	(data_obj *) 0,                 /* M-+ */
	(data_obj *) 0,                 /* M-, */
	(data_obj *) 0,                 /* M-- */
	(data_obj *) 0,                 /* M-. */
	(data_obj *) 0,                 /* M-/ */
	(data_obj *) 0,                 /* M-0 */
	(data_obj *) 0,                 /* M-1 */
	(data_obj *) 0,                 /* M-2 */
	(data_obj *) 0,                 /* M-3 */
	(data_obj *) 0,                 /* M-4 */
	(data_obj *) 0,                 /* M-5 */
	(data_obj *) 0,                 /* M-6 */
	(data_obj *) 0,                 /* M-7 */
	(data_obj *) 0,                 /* M-8 */
	(data_obj *) 0,                 /* M-9 */
	(data_obj *) 0,                 /* M-: */
	(data_obj *) 0,                 /* M-; */
	(data_obj *) 0,                 /* M-< */
	(data_obj *) 0,                 /* M-= */
	(data_obj *) 0,                 /* M-> */
	(data_obj *) 0,                 /* M-? */
	(data_obj *) 0,                 /* M-@ */
	(data_obj *) 0,                 /* M-A */
	(data_obj *) 0,                 /* M-B */
	(data_obj *) 0,                 /* M-C */
	(data_obj *) 0,                 /* M-D */
	(data_obj *) 0,                 /* M-E */
	(data_obj *) 0,                 /* M-F */
	(data_obj *) 0,                 /* M-G */
	(data_obj *) 0,                 /* M-H */
	(data_obj *) 0,                 /* M-I */
	(data_obj *) 0,                 /* M-J */
	(data_obj *) 0,                 /* M-K */
	(data_obj *) 0,                 /* M-L */
	(data_obj *) 0,                 /* M-M */
	(data_obj *) 0,                 /* M-N */
	(data_obj *) 0,                 /* M-O */
	(data_obj *) 0,                 /* M-P */
	(data_obj *) 0,                 /* M-Q */
	(data_obj *) 0,                 /* M-R */
	(data_obj *) 0,                 /* M-S */
	(data_obj *) 0,                 /* M-T */
	(data_obj *) 0,                 /* M-U */
	(data_obj *) 0,                 /* M-V */
	(data_obj *) 0,                 /* M-W */
	(data_obj *) 0,                 /* M-X */
	(data_obj *) 0,                 /* M-Y */
	(data_obj *) 0,                 /* M-Z */
	(data_obj *) 0,                 /* M-[ */
	(data_obj *) 0,                 /* M-\ */
	(data_obj *) 0,                 /* M-] */
	(data_obj *) 0,                 /* M-^ */
	(data_obj *) 0,                 /* M-_ */
	(data_obj *) 0,                 /* M-` */
	(data_obj *) 0,                 /* M-a */
	(data_obj *) 0,                 /* M-b */
	(data_obj *) 0,                 /* M-c */
	(data_obj *) 0,                 /* M-d */
	(data_obj *) 0,                 /* M-e */
	(data_obj *) 0,                 /* M-f */
	(data_obj *) 0,                 /* M-g */
	(data_obj *) 0,                 /* M-h */
	(data_obj *) 0,                 /* M-i */
	(data_obj *) 0,                 /* M-j */
	(data_obj *) 0,                 /* M-k */
	(data_obj *) 0,                 /* M-l */
	(data_obj *) 0,                 /* M-m */
	(data_obj *) 0,                 /* M-n */
	(data_obj *) 0,                 /* M-o */
	(data_obj *) 0,                 /* M-p */
	(data_obj *) 0,                 /* M-q */
	(data_obj *) 0,                 /* M-r */
	(data_obj *) 0,                 /* M-s */
	(data_obj *) 0,                 /* M-t */
	(data_obj *) 0,                 /* M-u */
	(data_obj *) 0,                 /* M-v */
	(data_obj *) 0,                 /* M-w */
	(data_obj *) 0,                 /* M-x */
	(data_obj *) 0,                 /* M-y */
	(data_obj *) 0,                 /* M-z */
	(data_obj *) 0,                 /* M-{ */
	(data_obj *) 0,                 /* M-| */
	(data_obj *) 0,                 /* M-} */
	(data_obj *) 0,                 /* M-~ */
	(data_obj *) 0,                 /* M-^? */
#endif /* ASCII */
};

data_obj	*CtlxKeys[NCHARS] = {
	(data_obj *) 0,                 /* C-@ */
	(data_obj *) 0,                 /* C-A */
	(data_obj *) &commands[114],	/* C-B */
	(data_obj *) &commands[76],	/* C-C */
	(data_obj *) 0,                 /* C-D */
	(data_obj *) &commands[33],	/* C-E */
	(data_obj *) &commands[81],	/* C-F */
	(data_obj *) 0,                 /* C-G */
	(data_obj *) &commands[109],	/* C-H */
	(data_obj *) &commands[100],	/* C-I */
	(data_obj *) 0,                 /* C-J */
	(data_obj *) 0,                 /* C-K */
	(data_obj *) 0,                 /* C-L */
	(data_obj *) &commands[209],	/* C-M */
	(data_obj *) &commands[123],	/* C-N */
	(data_obj *) &commands[41],	/* C-O */
	(data_obj *) &commands[135],	/* C-P */
	(data_obj *) 0,                 /* C-Q */
	(data_obj *) &commands[203],	/* C-R */
	(data_obj *) &commands[158],	/* C-S */
	(data_obj *) &commands[199],	/* C-T */
	(data_obj *) 0,                 /* C-U */
	(data_obj *) &commands[81],	/* C-V */
	(data_obj *) &commands[207],	/* C-W */
	(data_obj *) &commands[72],	/* C-X */
	(data_obj *) 0,                 /* C-Y */
	(data_obj *) 0,                 /* C-Z */
	(data_obj *) 0,                 /* ESC */
	(data_obj *) &commands[158],	/* C-\ */
	(data_obj *) 0,                 /* C-] */
	(data_obj *) 0,                 /* C-^ */
	(data_obj *) 0,                 /* C-_ */
	(data_obj *) 0,                 /*   */
	(data_obj *) &commands[144],	/* ! */
	(data_obj *) 0,                 /* " */
	(data_obj *) 0,                 /* # */
	(data_obj *) 0,                 /* $ */
	(data_obj *) 0,                 /* % */
	(data_obj *) 0,                 /* & */
	(data_obj *) 0,                 /* ' */
	(data_obj *) &commands[14],	/* ( */
	(data_obj *) &commands[67],	/* ) */
	(data_obj *) 0,                 /* * */
	(data_obj *) 0,                 /* + */
	(data_obj *) 0,                 /* , */
	(data_obj *) 0,                 /* - */
	(data_obj *) 0,                 /* . */
	(data_obj *) 0,                 /* / */
	(data_obj *) 0,                 /* 0 */
	(data_obj *) &commands[45],	/* 1 */
	(data_obj *) &commands[193],	/* 2 */
	(data_obj *) 0,                 /* 3 */
	(data_obj *) &commands[204],	/* 4 */
	(data_obj *) 0,                 /* 5 */
	(data_obj *) 0,                 /* 6 */
	(data_obj *) 0,                 /* 7 */
	(data_obj *) 0,                 /* 8 */
	(data_obj *) 0,                 /* 9 */
	(data_obj *) 0,                 /* : */
	(data_obj *) 0,                 /* ; */
	(data_obj *) 0,                 /* < */
	(data_obj *) &commands[22],	/* = */
	(data_obj *) 0,                 /* > */
	(data_obj *) &commands[51],	/* ? */
	(data_obj *) 0,                 /* @ */
	(data_obj *) 0,                 /* A */
	(data_obj *) &commands[169],	/* B */
	(data_obj *) 0,                 /* C */
	(data_obj *) &commands[48],	/* D */
	(data_obj *) &commands[74],	/* E */
	(data_obj *) 0,                 /* F */
	(data_obj *) 0,                 /* G */
	(data_obj *) 0,                 /* H */
	(data_obj *) 0,                 /* I */
	(data_obj *) 0,                 /* J */
	(data_obj *) &commands[42],	/* K */
	(data_obj *) 0,                 /* L */
	(data_obj *) 0,                 /* M */
	(data_obj *) &commands[126],	/* N */
	(data_obj *) &commands[138],	/* O */
	(data_obj *) &commands[138],	/* P */
	(data_obj *) 0,                 /* Q */
	(data_obj *) 0,                 /* R */
	(data_obj *) &commands[144],	/* S */
	(data_obj *) &commands[82],	/* T */
	(data_obj *) 0,                 /* U */
	(data_obj *) 0,                 /* V */
	(data_obj *) 0,                 /* W */
	(data_obj *) 0,                 /* X */
	(data_obj *) 0,                 /* Y */
	(data_obj *) 0,                 /* Z */
	(data_obj *) 0,                 /* [ */
	(data_obj *) 0,                 /* \ */
	(data_obj *) 0,                 /* ] */
	(data_obj *) &commands[96],	/* ^ */
	(data_obj *) 0,                 /* _ */
	(data_obj *) 0,                 /* ` */
	(data_obj *) 0,                 /* a */
	(data_obj *) &commands[169],	/* b */
	(data_obj *) 0,                 /* c */
	(data_obj *) &commands[48],	/* d */
	(data_obj *) &commands[74],	/* e */
	(data_obj *) 0,                 /* f */
	(data_obj *) 0,                 /* g */
	(data_obj *) 0,                 /* h */
	(data_obj *) 0,                 /* i */
	(data_obj *) 0,                 /* j */
	(data_obj *) &commands[42],	/* k */
	(data_obj *) 0,                 /* l */
	(data_obj *) 0,                 /* m */
	(data_obj *) &commands[126],	/* n */
	(data_obj *) &commands[138],	/* o */
	(data_obj *) &commands[138],	/* p */
	(data_obj *) 0,                 /* q */
	(data_obj *) 0,                 /* r */
	(data_obj *) &commands[144],	/* s */
	(data_obj *) &commands[82],	/* t */
	(data_obj *) 0,                 /* u */
	(data_obj *) 0,                 /* v */
	(data_obj *) 0,                 /* w */
	(data_obj *) 0,                 /* x */
	(data_obj *) 0,                 /* y */
	(data_obj *) 0,                 /* z */
	(data_obj *) 0,                 /* { */
	(data_obj *) &commands[186],	/* | */
	(data_obj *) 0,                 /* } */
	(data_obj *) 0,                 /* ~ */
#ifdef ASCII
	(data_obj *) &commands[109],	/* ^? */
#else /* IBMPC or MAC */
	(data_obj *) &commands[109],	/* ^? */
	(data_obj *) 0,                 /* M-C-@ */
	(data_obj *) 0,                 /* M-C-A */
	(data_obj *) 0,                 /* M-C-B */
	(data_obj *) 0,                 /* M-C-C */
	(data_obj *) 0,                 /* M-C-D */
	(data_obj *) 0,                 /* M-C-E */
	(data_obj *) 0,                 /* M-C-F */
	(data_obj *) 0,                 /* M-C-G */
	(data_obj *) 0,                 /* M-C-H */
	(data_obj *) 0,                 /* M-C-I */
	(data_obj *) 0,                 /* M-C-J */
	(data_obj *) 0,                 /* M-C-K */
	(data_obj *) 0,                 /* M-C-L */
	(data_obj *) 0,                 /* M-C-M */
	(data_obj *) 0,                 /* M-C-N */
	(data_obj *) 0,                 /* M-C-O */
	(data_obj *) 0,                 /* M-C-P */
	(data_obj *) 0,                 /* M-C-Q */
	(data_obj *) 0,                 /* M-C-R */
	(data_obj *) 0,                 /* M-C-S */
	(data_obj *) 0,                 /* M-C-T */
	(data_obj *) 0,                 /* M-C-U */
	(data_obj *) 0,                 /* M-C-V */
	(data_obj *) 0,                 /* M-C-W */
	(data_obj *) 0,                 /* M-C-X */
	(data_obj *) 0,                 /* M-C-Y */
	(data_obj *) 0,                 /* M-C-Z */
	(data_obj *) 0,                 /* M-ESC */
	(data_obj *) 0,                 /* M-C-\ */
	(data_obj *) 0,                 /* M-C-] */
	(data_obj *) 0,                 /* M-C-^ */
	(data_obj *) 0,                 /* M-C-_ */
	(data_obj *) 0,                 /* M-  */
	(data_obj *) 0,                 /* M-! */
	(data_obj *) 0,                 /* M-" */
	(data_obj *) 0,                 /* M-# */
	(data_obj *) 0,                 /* M-$ */
	(data_obj *) 0,                 /* M-% */
	(data_obj *) 0,                 /* M-& */
	(data_obj *) 0,                 /* M-' */
	(data_obj *) 0,                 /* M-( */
	(data_obj *) 0,                 /* M-) */
	(data_obj *) 0,                 /* M-* */
	(data_obj *) 0,                 /* M-+ */
	(data_obj *) 0,                 /* M-, */
	(data_obj *) 0,                 /* M-- */
	(data_obj *) 0,                 /* M-. */
	(data_obj *) 0,                 /* M-/ */
	(data_obj *) 0,                 /* M-0 */
	(data_obj *) 0,                 /* M-1 */
	(data_obj *) 0,                 /* M-2 */
	(data_obj *) 0,                 /* M-3 */
	(data_obj *) 0,                 /* M-4 */
	(data_obj *) 0,                 /* M-5 */
	(data_obj *) 0,                 /* M-6 */
	(data_obj *) 0,                 /* M-7 */
	(data_obj *) 0,                 /* M-8 */
	(data_obj *) 0,                 /* M-9 */
	(data_obj *) 0,                 /* M-: */
	(data_obj *) 0,                 /* M-; */
	(data_obj *) 0,                 /* M-< */
	(data_obj *) 0,                 /* M-= */
	(data_obj *) 0,                 /* M-> */
	(data_obj *) 0,                 /* M-? */
	(data_obj *) 0,                 /* M-@ */
	(data_obj *) 0,                 /* M-A */
	(data_obj *) 0,                 /* M-B */
	(data_obj *) 0,                 /* M-C */
	(data_obj *) 0,                 /* M-D */
	(data_obj *) 0,                 /* M-E */
	(data_obj *) 0,                 /* M-F */
	(data_obj *) 0,                 /* M-G */
	(data_obj *) 0,                 /* M-H */
	(data_obj *) 0,                 /* M-I */
	(data_obj *) 0,                 /* M-J */
	(data_obj *) 0,                 /* M-K */
	(data_obj *) 0,                 /* M-L */
	(data_obj *) 0,                 /* M-M */
	(data_obj *) 0,                 /* M-N */
	(data_obj *) 0,                 /* M-O */
	(data_obj *) 0,                 /* M-P */
	(data_obj *) 0,                 /* M-Q */
	(data_obj *) 0,                 /* M-R */
	(data_obj *) 0,                 /* M-S */
	(data_obj *) 0,                 /* M-T */
	(data_obj *) 0,                 /* M-U */
	(data_obj *) 0,                 /* M-V */
	(data_obj *) 0,                 /* M-W */
	(data_obj *) 0,                 /* M-X */
	(data_obj *) 0,                 /* M-Y */
	(data_obj *) 0,                 /* M-Z */
	(data_obj *) 0,                 /* M-[ */
	(data_obj *) 0,                 /* M-\ */
	(data_obj *) 0,                 /* M-] */
	(data_obj *) 0,                 /* M-^ */
	(data_obj *) 0,                 /* M-_ */
	(data_obj *) 0,                 /* M-` */
	(data_obj *) 0,                 /* M-a */
	(data_obj *) 0,                 /* M-b */
	(data_obj *) 0,                 /* M-c */
	(data_obj *) 0,                 /* M-d */
	(data_obj *) 0,                 /* M-e */
	(data_obj *) 0,                 /* M-f */
	(data_obj *) 0,                 /* M-g */
	(data_obj *) 0,                 /* M-h */
	(data_obj *) 0,                 /* M-i */
	(data_obj *) 0,                 /* M-j */
	(data_obj *) 0,                 /* M-k */
	(data_obj *) 0,                 /* M-l */
	(data_obj *) 0,                 /* M-m */
	(data_obj *) 0,                 /* M-n */
	(data_obj *) 0,                 /* M-o */
	(data_obj *) 0,                 /* M-p */
	(data_obj *) 0,                 /* M-q */
	(data_obj *) 0,                 /* M-r */
	(data_obj *) 0,                 /* M-s */
	(data_obj *) 0,                 /* M-t */
	(data_obj *) 0,                 /* M-u */
	(data_obj *) 0,                 /* M-v */
	(data_obj *) 0,                 /* M-w */
	(data_obj *) 0,                 /* M-x */
	(data_obj *) 0,                 /* M-y */
	(data_obj *) 0,                 /* M-z */
	(data_obj *) 0,                 /* M-{ */
	(data_obj *) 0,                 /* M-| */
	(data_obj *) 0,                 /* M-} */
	(data_obj *) 0,                 /* M-~ */
	(data_obj *) 0,                 /* M-^? */
#endif /* ASCII */
};

#ifdef IBMPC
data_obj	*MiscKeys[NCHARS] = {
	(data_obj *) 0,                 /* C-@ */
	(data_obj *) 0,                 /* C-A */
	(data_obj *) 0,                 /* C-B */
	(data_obj *) &commands[182],	/* C-C */
	(data_obj *) 0,                 /* C-D */
	(data_obj *) 0,                 /* C-E */
	(data_obj *) 0,                 /* C-F */
	(data_obj *) 0,                 /* C-G */
	(data_obj *) 0,                 /* C-H */
	(data_obj *) 0,                 /* C-I */
	(data_obj *) 0,                 /* C-J */
	(data_obj *) 0,                 /* C-K */
	(data_obj *) 0,                 /* C-L */
	(data_obj *) 0,                 /* C-M */
	(data_obj *) 0,                 /* C-N */
	(data_obj *) 0,                 /* C-O */
	(data_obj *) &commands[147],	/* C-P */
	(data_obj *) &commands[34],	/* C-Q */
	(data_obj *) &commands[89],	/* C-R */
	(data_obj *) &commands[156],	/* C-S */
	(data_obj *) 0,                 /* C-T */
	(data_obj *) &commands[212],	/* C-U */
	(data_obj *) &commands[29],	/* C-V */
	(data_obj *) &commands[118],	/* C-W */
	(data_obj *) 0,                 /* C-X */
	(data_obj *) 0,                 /* C-Y */
	(data_obj *) 0,                 /* C-Z */
	(data_obj *) 0,                 /* ESC */
	(data_obj *) 0,                 /* C-\ */
	(data_obj *) 0,                 /* C-] */
	(data_obj *) &commands[11],	/* C-^ */
	(data_obj *) 0,                 /* C-_ */
	(data_obj *) &commands[103],	/*   */
	(data_obj *) &commands[90],	/* ! */
	(data_obj *) &commands[94],	/* " */
	(data_obj *) 0,                 /* # */
	(data_obj *) &commands[78],	/* $ */
	(data_obj *) &commands[111],	/* % */
	(data_obj *) &commands[28],	/* & */
	(data_obj *) 0,                 /* ' */
	(data_obj *) 0,                 /* ( */
	(data_obj *) 0,                 /* ) */
	(data_obj *) 0,                 /* * */
	(data_obj *) 0,                 /* + */
	(data_obj *) &commands[159],	/* , */
	(data_obj *) &commands[73],	/* - */
	(data_obj *) &commands[27],	/* . */
	(data_obj *) &commands[137],	/* / */
	(data_obj *) &commands[13],	/* 0 */
	(data_obj *) 0,                 /* 1 */
	(data_obj *) &commands[84],	/* 2 */
	(data_obj *) 0,                 /* 3 */
	(data_obj *) 0,                 /* 4 */
	(data_obj *) 0,                 /* 5 */
	(data_obj *) 0,                 /* 6 */
	(data_obj *) 0,                 /* 7 */
	(data_obj *) 0,                 /* 8 */
	(data_obj *) 0,                 /* 9 */
	(data_obj *) 0,                 /* : */
	(data_obj *) 0,                 /* ; */
	(data_obj *) 0,                 /* < */
	(data_obj *) 0,                 /* = */
	(data_obj *) 0,                 /* > */
	(data_obj *) 0,                 /* ? */
	(data_obj *) 0,                 /* @ */
	(data_obj *) 0,                 /* A */
	(data_obj *) 0,                 /* B */
	(data_obj *) 0,                 /* C */
	(data_obj *) 0,                 /* D */
	(data_obj *) 0,                 /* E */
	(data_obj *) 0,                 /* F */
	(data_obj *) &commands[16],	/* G */
	(data_obj *) &commands[136],	/* H */
	(data_obj *) &commands[137],	/* I */
	(data_obj *) 0,                 /* J */
	(data_obj *) &commands[7],	/* K */
	(data_obj *) 0,                 /* L */
	(data_obj *) &commands[85],	/* M */
	(data_obj *) 0,                 /* N */
	(data_obj *) &commands[69],	/* O */
	(data_obj *) &commands[124],	/* P */
	(data_obj *) &commands[125],	/* Q */
	(data_obj *) &commands[128],	/* R */
	(data_obj *) &commands[44],	/* S */
	(data_obj *) 0,                 /* T */
	(data_obj *) 0,                 /* U */
	(data_obj *) 0,                 /* V */
	(data_obj *) 0,                 /* W */
	(data_obj *) 0,                 /* X */
	(data_obj *) 0,                 /* Y */
	(data_obj *) 0,                 /* Z */
	(data_obj *) 0,                 /* [ */
	(data_obj *) 0,                 /* \ */
	(data_obj *) 0,                 /* ] */
	(data_obj *) 0,                 /* ^ */
	(data_obj *) 0,                 /* _ */
	(data_obj *) 0,                 /* ` */
	(data_obj *) 0,                 /* a */
	(data_obj *) 0,                 /* b */
	(data_obj *) 0,                 /* c */
	(data_obj *) 0,                 /* d */
	(data_obj *) 0,                 /* e */
	(data_obj *) 0,                 /* f */
	(data_obj *) 0,                 /* g */
	(data_obj *) 0,                 /* h */
	(data_obj *) 0,                 /* i */
	(data_obj *) 0,                 /* j */
	(data_obj *) 0,                 /* k */
	(data_obj *) 0,                 /* l */
	(data_obj *) 0,                 /* m */
	(data_obj *) 0,                 /* n */
	(data_obj *) 0,                 /* o */
	(data_obj *) 0,                 /* p */
	(data_obj *) 0,                 /* q */
	(data_obj *) 0,                 /* r */
	(data_obj *) &commands[13],	/* s */
	(data_obj *) &commands[90],	/* t */
	(data_obj *) &commands[68],	/* u */
	(data_obj *) &commands[126],	/* v */
	(data_obj *) &commands[15],	/* w */
	(data_obj *) &commands[170],	/* x */
	(data_obj *) &commands[171],	/* y */
	(data_obj *) &commands[172],	/* z */
	(data_obj *) &commands[173],	/* { */
	(data_obj *) &commands[174],	/* | */
	(data_obj *) &commands[175],	/* } */
	(data_obj *) &commands[176],	/* ~ */
	(data_obj *) &commands[177],	/* ^? */
	(data_obj *) &commands[178],	/* M-C-@ */
	(data_obj *) &commands[179],	/* M-C-A */
	(data_obj *) 0,                 /* M-C-B */
	(data_obj *) 0,                 /* M-C-C */
	(data_obj *) &commands[138],	/* M-C-D */
	(data_obj *) 0,                 /* M-C-E */
	(data_obj *) 0,                 /* M-C-F */
	(data_obj *) 0,                 /* M-C-G */
	(data_obj *) 0,                 /* M-C-H */
	(data_obj *) 0,                 /* M-C-I */
	(data_obj *) 0,                 /* M-C-J */
	(data_obj *) 0,                 /* M-C-K */
	(data_obj *) 0,                 /* M-C-L */
	(data_obj *) 0,                 /* M-C-M */
	(data_obj *) 0,                 /* M-C-N */
	(data_obj *) 0,                 /* M-C-O */
	(data_obj *) 0,                 /* M-C-P */
	(data_obj *) 0,                 /* M-C-Q */
	(data_obj *) 0,                 /* M-C-R */
	(data_obj *) 0,                 /* M-C-S */
	(data_obj *) 0,                 /* M-C-T */
	(data_obj *) 0,                 /* M-C-U */
	(data_obj *) 0,                 /* M-C-V */
	(data_obj *) 0,                 /* M-C-W */
	(data_obj *) 0,                 /* M-C-X */
	(data_obj *) 0,                 /* M-C-Y */
	(data_obj *) 0,                 /* M-C-Z */
	(data_obj *) 0,                 /* M-ESC */
	(data_obj *) 0,                 /* M-C-\ */
	(data_obj *) 0,                 /* M-C-] */
	(data_obj *) 0,                 /* M-C-^ */
	(data_obj *) 0,                 /* M-C-_ */
	(data_obj *) 0,                 /* M-  */
	(data_obj *) 0,                 /* M-! */
	(data_obj *) 0,                 /* M-" */
	(data_obj *) 0,                 /* M-# */
	(data_obj *) 0,                 /* M-$ */
	(data_obj *) 0,                 /* M-% */
	(data_obj *) 0,                 /* M-& */
	(data_obj *) 0,                 /* M-' */
	(data_obj *) 0,                 /* M-( */
	(data_obj *) 0,                 /* M-) */
	(data_obj *) 0,                 /* M-* */
	(data_obj *) 0,                 /* M-+ */
	(data_obj *) 0,                 /* M-, */
	(data_obj *) 0,                 /* M-- */
	(data_obj *) 0,                 /* M-. */
	(data_obj *) 0,                 /* M-/ */
	(data_obj *) 0,                 /* M-0 */
	(data_obj *) 0,                 /* M-1 */
	(data_obj *) 0,                 /* M-2 */
	(data_obj *) 0,                 /* M-3 */
	(data_obj *) 0,                 /* M-4 */
	(data_obj *) 0,                 /* M-5 */
	(data_obj *) 0,                 /* M-6 */
	(data_obj *) 0,                 /* M-7 */
	(data_obj *) 0,                 /* M-8 */
	(data_obj *) 0,                 /* M-9 */
	(data_obj *) 0,                 /* M-: */
	(data_obj *) 0,                 /* M-; */
	(data_obj *) 0,                 /* M-< */
	(data_obj *) 0,                 /* M-= */
	(data_obj *) 0,                 /* M-> */
	(data_obj *) 0,                 /* M-? */
	(data_obj *) 0,                 /* M-@ */
	(data_obj *) 0,                 /* M-A */
	(data_obj *) 0,                 /* M-B */
	(data_obj *) 0,                 /* M-C */
	(data_obj *) 0,                 /* M-D */
	(data_obj *) 0,                 /* M-E */
	(data_obj *) 0,                 /* M-F */
	(data_obj *) 0,                 /* M-G */
	(data_obj *) 0,                 /* M-H */
	(data_obj *) 0,                 /* M-I */
	(data_obj *) 0,                 /* M-J */
	(data_obj *) 0,                 /* M-K */
	(data_obj *) 0,                 /* M-L */
	(data_obj *) 0,                 /* M-M */
	(data_obj *) 0,                 /* M-N */
	(data_obj *) 0,                 /* M-O */
	(data_obj *) 0,                 /* M-P */
	(data_obj *) 0,                 /* M-Q */
	(data_obj *) 0,                 /* M-R */
	(data_obj *) 0,                 /* M-S */
	(data_obj *) 0,                 /* M-T */
	(data_obj *) 0,                 /* M-U */
	(data_obj *) 0,                 /* M-V */
	(data_obj *) 0,                 /* M-W */
	(data_obj *) 0,                 /* M-X */
	(data_obj *) 0,                 /* M-Y */
	(data_obj *) 0,                 /* M-Z */
	(data_obj *) 0,                 /* M-[ */
	(data_obj *) 0,                 /* M-\ */
	(data_obj *) 0,                 /* M-] */
	(data_obj *) 0,                 /* M-^ */
	(data_obj *) 0,                 /* M-_ */
	(data_obj *) 0,                 /* M-` */
	(data_obj *) 0,                 /* M-a */
	(data_obj *) 0,                 /* M-b */
	(data_obj *) 0,                 /* M-c */
	(data_obj *) 0,                 /* M-d */
	(data_obj *) 0,                 /* M-e */
	(data_obj *) 0,                 /* M-f */
	(data_obj *) 0,                 /* M-g */
	(data_obj *) 0,                 /* M-h */
	(data_obj *) 0,                 /* M-i */
	(data_obj *) 0,                 /* M-j */
	(data_obj *) 0,                 /* M-k */
	(data_obj *) 0,                 /* M-l */
	(data_obj *) 0,                 /* M-m */
	(data_obj *) 0,                 /* M-n */
	(data_obj *) 0,                 /* M-o */
	(data_obj *) 0,                 /* M-p */
	(data_obj *) 0,                 /* M-q */
	(data_obj *) 0,                 /* M-r */
	(data_obj *) 0,                 /* M-s */
	(data_obj *) 0,                 /* M-t */
	(data_obj *) 0,                 /* M-u */
	(data_obj *) 0,                 /* M-v */
	(data_obj *) 0,                 /* M-w */
	(data_obj *) 0,                 /* M-x */
	(data_obj *) 0,                 /* M-y */
	(data_obj *) 0,                 /* M-z */
	(data_obj *) 0,                 /* M-{ */
	(data_obj *) 0,                 /* M-| */
	(data_obj *) 0,                 /* M-} */
	(data_obj *) 0,                 /* M-~ */
	(data_obj *) 0,                 /* M-^? */
};
#endif /* IBMPC */
